### ISSUE TITLE
Incorrect node.js example code

### ISSUE THREAD

**Issue by bwentwor** [IBM-Bluemix-Docs/appid#1]
On Twitter, we received a complaint from a customer that a node.js example is incorrect. The incorrect information exists on the following page: https://console.bluemix.net/docs/services/appid/existing.html#adding-app-id-to-an-existing-app

Here is the information that needs to be addressed:
"Up til midnight trying to get AppID to work with node.js then find there was a typo in the Bluemix docs sample code"

"opening bracket missing for Node.js example code, on the line starting app.get("/protected"..."

FYI - @smguilia If you do not own this documentation, can you please redirect it to the correct person? Thanks!

**Comment by smguilia** [comment]
@bwentwor Will verify with Dev and get it fixed today. Thanks Bill!

**Comment by smguilia** [comment]
Found the error. Fixed it. I have content in the file that cannot be sent out until I get clearance from the team. Should happen relatively quickly. Will let you know when the fix is in prod.

**Comment by smguilia** [comment]
This is in production. Sorry! Forgot to come back and post.
