### ISSUE TITLE
bluemix-appid is deprecated

### ISSUE THREAD

**Issue by afrittoli** [IBM-Bluemix-Docs/appid#243]
We should probably switch the docs to use ibmcloud-appid in the nodejs section:

```
$ npm install passport express bluemix-appid
npm WARN deprecated bluemix-appid@3.0.6: The usage of this package is deprecated. To leverage new App ID functionality, make a few small changes in your apps to use the ibmcloud-appid package.
```

**Comment by smguilia** [comment]
Hi @afrittoli Thanks for leaving me some feedback! I'm looking into this, and the other issue and will let you know when they are resolved.

**Comment by smguilia** [comment]
This is fixed and will go out in the next prod push.
